#!/bin/bash
#
# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e -v
cd "`dirname $0`/.."

PATH=./scripts:./node_modules/.bin:$PATH

SRC=src
DIST=dist
VERSION=`get-version`
PREAMBLE=`sed s/VERSION_STRING/$VERSION/ $SRC/preamble.js`

mkdir -p $DIST

make-version

make-swf $DIST/marzipano.swf

browserify \
  --noparse=node_modules/**/*.js \
  -t glslify \
  -s Marzipano \
  -o $DIST/marzipano.js \
  $SRC/index.js

uglifyjs $DIST/marzipano.js -o $DIST/marzipano.js \
  -m -c warnings=false --preamble "$PREAMBLE"
