#!/bin/bash
set -v -e -u -o pipefail
cd "`dirname $0`/.."

# https://cloud.google.com/storage/docs/gsutil/commands/rsync
# -m to perform parallel operations (good for many files)
gsutil -m cp -r docs/* gs://www.marzipano.net/reference